name: my_study_life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: ^3.2.0
  syncfusion_flutter_calendar: ^28.2.9
  animated_bottom_navigation_bar: ^1.4.0
  dotted_border: ^2.1.0
  material_symbols_icons: ^4.2810.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets :
   - assets/images/